// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCcRmNiGfFwn4nsVt6vKsONJthFfo57Q',
    appId: '1:274385991118:web:e19d6d87232c0876dda79f',
    messagingSenderId: '274385991118',
    projectId: 'reklama-aded8',
    authDomain: 'reklama-aded8.firebaseapp.com',
    storageBucket: 'reklama-aded8.appspot.com',
    measurementId: 'G-8BN5TL2EM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwOJpiPYDlQWHyuRLqlnWMUgvE4bYIArg',
    appId: '1:274385991118:android:6618cb25684337bbdda79f',
    messagingSenderId: '274385991118',
    projectId: 'reklama-aded8',
    storageBucket: 'reklama-aded8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEKUFFOCCMqF-yDfSDxLd5TIczH-hFuQU',
    appId: '1:274385991118:ios:4fbe3f49b303d87ddda79f',
    messagingSenderId: '274385991118',
    projectId: 'reklama-aded8',
    storageBucket: 'reklama-aded8.appspot.com',
    iosClientId: '274385991118-embq3n4c4h4t4m1ko5qog2uhbfnvh246.apps.googleusercontent.com',
    iosBundleId: 'com.example.reklama',
  );
}
